-- MySQL Script generated by MySQL Workbench
-- Fri Jun 30 11:53:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ShopPrimeBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ShopPrimeBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ShopPrimeBD` DEFAULT CHARACTER SET utf8;
USE `ShopPrimeBD` ;

-- -----------------------------------------------------
-- Table `ShopPrimeBD`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopPrimeBD`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `ApPaterno` VARCHAR(45) NULL,
  `ApMaterno` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `Foto` BLOB NULL,
  `nombrefoto` VARCHAR(45) NULL,
  `estatusUsuario` TINYINT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShopPrimeBD`.`RolUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopPrimeBD`.`RolUsuario` (
  `idRolUsuario` INT NOT NULL AUTO_INCREMENT,
  `NombreRol` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`idRolUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShopPrimeBD`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShopPrimeBD`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `NombreLogin` VARCHAR(45) NULL,
  `ClaveLogin` VARCHAR(256) NULL,
  `Fechacreacion` DATE NULL,
  `estatusLogin` TINYINT NULL,
  `idUsuario` INT NULL,
  `idRolUsuario` INT NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `Fk_Login_RolUsuario_idx` (`idRolUsuario` ASC),
  INDEX `Fk_Login_Usuario_idx` (`idUsuario` ASC),
  CONSTRAINT `Fk_Login_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ShopPrimeBD`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_Login_RolUsuario`
    FOREIGN KEY (`idRolUsuario`)
    REFERENCES `ShopPrimeBD`.`RolUsuario` (`idRolUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ShopPrimeBD`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `ShopPrimeBD`;
INSERT INTO `ShopPrimeBD`.`Usuario` (`idUsuario`, `Nombre`, `ApPaterno`, `ApMaterno`, `email`, `telefono`, `Foto`, `nombrefoto`, `estatusUsuario`) VALUES (1, 'Valentina', 'Perez', 'Barrios', 'minjean472@gmail.com', '5578435457', NULL, 'Valentina.jpg', true);
INSERT INTO `ShopPrimeBD`.`Usuario` (`idUsuario`, `Nombre`, `ApPaterno`, `ApMaterno`, `email`, `telefono`, `Foto`, `nombrefoto`, `estatusUsuario`) VALUES (2, 'Brisa', 'Corona', 'Acevedo', 'brissa@gmail.com', '7731551168', NULL, 'Brisa.jpg', true);
INSERT INTO `ShopPrimeBD`.`Usuario` (`idUsuario`, `Nombre`, `ApPaterno`, `ApMaterno`, `email`, `telefono`, `Foto`, `nombrefoto`, `estatusUsuario`) VALUES (3, 'Evelyn', 'Nava', 'Sanchez', 'navaximena@gmail.com', '7731845520', NULL, 'Evelyn.jpg', true);
;
COMMIT;

select * from Usuario;
-- -----------------------------------------------------
-- Data for table `ShopPrimeBD`.`RolUsuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `ShopPrimeBD`;
INSERT INTO `ShopPrimeBD`.`RolUsuario` (`idRolUsuario`, `NombreRol`, `Descripcion`) VALUES (1, 'Administrador', 'Tiene todos los permisos');
INSERT INTO `ShopPrimeBD`.`RolUsuario` (`idRolUsuario`, `NombreRol`, `Descripcion`) VALUES (2, 'Clientes', 'Permisos de consultas');

COMMIT;
select * from  RolUsuario;


-- -----------------------------------------------------
-- Data for table `ShopPrimeBD`.`Login`
-- -----------------------------------------------------
START TRANSACTION;
USE `ShopPrimeBD`;sp_crearCuenta
INSERT INTO `ShopPrimeBD`.`Login` (`idLogin`, `NombreLogin`, `ClaveLogin`, `Fechacreacion`, `estatusLogin`, `idUsuario`, `idRolUsuario`) VALUES (1, 'Valentina', '123456', '2023-06-30', true, 1, 1);
INSERT INTO `ShopPrimeBD`.`Login` (`idLogin`, `NombreLogin`, `ClaveLogin`, `Fechacreacion`, `estatusLogin`, `idUsuario`, `idRolUsuario`) VALUES (2, 'Brisa', '123', '2023-06-30', true, 2, 2);
INSERT INTO `ShopPrimeBD`.`Login` (`idLogin`, `NombreLogin`, `ClaveLogin`, `Fechacreacion`, `estatusLogin`, `idUsuario`, `idRolUsuario`) VALUES (3, 'Evelyn', '1234', '2023-06-30', true, 3, 2);

COMMIT;

select * from login;